### HEY SERVER
GET http://localhost:8000/

### POST SLACK EVENTS CALLBACK
POST http://localhost:8000/events/-/slack/callback/
Content-Type: "application/json"

{
	"token": "some-secure-token",
	"team_id": "some-team-id",
	"context_team_id": "some-team-id",
	"context_enterprise_id": null,
	"api_app_id": "some-app-id",
	"event": {
		"client_msg_id": "169fba12-e7db-4c7e-831b-19d603706aba",
		"type": "message",
		"text": "Hey",
		"user": "U03NGJTT5JT",
		"ts": "1691953744.751639",
		"blocks": [{
			"type": "rich_text",
			"block_id": "=7/Nx",
			"elements": [{
				"type": "rich_text_section",
				"elements": [{
					"type": "text",
					"text": "Hey"
				}]
			}]
		}],
		"team": "some-team-id",
		"channel": "C05L3H90PL2",
		"event_ts": "1691953744.751639",
		"channel_type": "channel"
	},
	"type": "event_callback",
	"event_id": "Ev05MLBBDPFC",
	"event_time": 1691953744,
	"authorizations": [{
		"enterprise_id": null,
		"team_id": "some-team-id",
		"user_id": "some-user-id",
		"is_bot": false,
		"is_enterprise_install": false
	}],
	"is_ext_shared_channel": false,
	"event_context": "some-unique-context-xyz"
}