import os

SLACK_APP_ID = os.getenv("SLACK_APP_ID", None)
SLACK_CLIENT_ID = os.getenv("SLACK_CLIENT_ID", None)
SLACK_CLIENT_SECRET = os.getenv("SLACK_CLIENT_SECRET", None)
SLACK_SIGNING_SECRET = os.getenv("SLACK_SIGNING_SECRET", None)
SLACK_VERIFICATION_TOKEN = os.getenv("SLACK_VERIFICATION_TOKEN", None)

SLACK_USER_OAUTH_TOKEN = os.getenv("SLACK_USER_OAUTH_TOKEN", None)
SLACK_BOT_OAUTH_TOKEN = os.getenv("SLACK_BOT_OAUTH_TOKEN", None)

POSTGRES_URI = os.getenv("POSTGRES_URI", None)
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379")

ZYG_BASE_URL = os.getenv("ZYG_BASE_URL", "http://localhost:8000")
