import os

SLACK_APP_ID = os.environ.get("SLACK_APP_ID")
SLACK_CLIENT_ID = os.environ.get("SLACK_CLIENT_ID")
SLACK_CLIENT_SECRET = os.environ.get("SLACK_CLIENT_SECRET")
SLACK_SIGNING_SECRET = os.environ.get("SLACK_SIGNING_SECRET")
SLACK_VERIFICATION_TOKEN = os.environ.get("SLACK_VERIFICATION_TOKEN")

SLACK_USER_OAUTH_TOKEN = os.environ.get("SLACK_USER_OAUTH_TOKEN")
SLACK_BOT_OAUTH_TOKEN = os.environ.get("SLACK_BOT_OAUTH_TOKEN")

POSTGRES_URI = os.environ.get("POSTGRES_URI")
